name: Create Daleel Keystore

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Create new keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore daleel-release.jks \
            -storetype JKS \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -alias daleel \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Daleel, OU=Daleel, O=Daleel, L=Port Sudan, ST=Red Sea, C=SD"

      - name: Create Base64 copy
        run: |
          base64 -w 0 daleel-release.jks > keystore-base64.txt

      - name: Upload keystore files
        uses: actions/upload-artifact@v4
        with:
          name: daleel-new-keystore
          path: |
            daleel-release.jks
            keystore-base64.txt
          retention-days: 1
